Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2018-08, with the labels that each got.

#165 Fix a mistranslation
  docs/t-sql/statements/create-external-file-format-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#164 Update setting-the-connection-properties.md
  docs/connect/jdbc/setting-the-connection-properties.md
Labels: Accepted, Linguistic Suggestion

#167 Update using-the-jdbc-driver.md
  docs/connect/jdbc/using-the-jdbc-driver.md
Labels: In Progress, Linguistic Suggestion

#168 dsn-connection-string-attribute.md
  docs/connect/odbc/dsn-connection-string-attribute.md
Labels: Accepted, Source Issue

#66 Update tutorial-sql-editor.md
  docs/sql-operations-studio/tutorial-sql-editor.md
Labels: In Progress, Linguistic Suggestion

#88 Update revoke-endpoint-permissions-transact-sql.md
  docs/t-sql/statements/revoke-endpoint-permissions-transact-sql.md
Labels: In Progress, Linguistic Suggestion

#171 Update basic-availability-groups-always-on-availability-groups.md
  docs/database-engine/availability-groups/windows/basic-availability-groups-always-on-availability-groups.md
Labels: Accepted, Linguistic Suggestion

#173 improve translations
  docs/relational-databases/performance/monitoring-performance-by-using-the-query-store.md
Labels: Accepted, Linguistic Suggestion

#175 Update tutorial-build-custom-insight-sql-server.md
  docs/sql-operations-studio/tutorial-build-custom-insight-sql-server.md
Labels: Accepted, Linguistic Suggestion

#176 Update wide-world-importers-dw-install-configure.md
  docs/samples/wide-world-importers-dw-install-configure.md
Labels: Accepted, Linguistic Suggestion

#177 Update automatic-tuning.md
  docs/relational-databases/automatic-tuning/automatic-tuning.md
Labels: Accepted, Linguistic Suggestion

#179 fix reserved characters
  docs/reporting-services/report-server/create-delete-or-modify-a-folder-web-portal.md
  docs/reporting-services/reports/upload-a-file-or-report-report-manager.md
Labels: Accepted, Source Issue

#178 Update pdo-exec.md
  docs/connect/php/pdo-exec.md
Labels: Accepted, Linguistic Suggestion

#180 Update cursor-types-sqlsrv-driver.md
  docs/connect/php/cursor-types-sqlsrv-driver.md
Labels: Linguistic Suggestion

#181 Update direct-statement-execution-prepared-statement-execution-pdo-sq…
  docs/connect/php/direct-statement-execution-prepared-statement-execution-pdo-sqlsrv-driver.md
Labels: Accepted, Linguistic Suggestion
