Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2019-09, with the labels that each got.

#631 Suggest to fix emphasis and improve translations
  docs/t-sql/functions/day-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#673 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msdistribution-history-transact-sql.md
Labels: Accepted

#672 Typo "@subscriber_db"→"subscriber_db"
  docs/relational-databases/system-tables/msdistribution-agents-transact-sql.md
Labels: Accepted

#670 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-originatorid-history-transact-sql.md
Labels: Accepted

#669 [LOC] Back-Translation "信頼されています。"→"trusted"
  docs/relational-databases/system-tables/msdistpublishers-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#671 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msdbms-map-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#674 fix "プッシュ サブスクリプションを削除します。"→"プッシュ サブスクリプションの削除"
  docs/relational-databases/system-stored-procedures/sp-mergesubscription-cleanup-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#675 [LOC] Back-Translation "匿名"→"anonymous"
  docs/relational-databases/system-stored-procedures/sp-dropmergesubscription-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#678 [LOC] Back-Translation "**配布**"→"**distribution**"
  docs/relational-databases/system-views/ihextendedarticleview-transact-sql.md
Labels: Accepted

#680 [LOC] Back-Translation "**場所**"→"**WHERE**"
  docs/odbc/reference/appendixes/processing-positioned-update-and-delete-statements.md
Labels: Accepted

#679 Suggest to fix 'pandas'
  docs/advanced-analytics/concepts/extension-python.md
  docs/advanced-analytics/python/python-libraries-and-data-types.md
  docs/advanced-analytics/python/ref-py-revoscalepy.md
  docs/advanced-analytics/python/setup-python-client-tools-sql.md
  docs/advanced-analytics/tutorials/python-ski-rental-linear-regression-prepare-data.md
  docs/advanced-analytics/tutorials/python-ski-rental-linear-regression-train-model.md
  docs/advanced-analytics/tutorials/quickstart-python-data-structures.md
  docs/advanced-analytics/tutorials/quickstart-python-inputs-and-outputs.md
  docs/advanced-analytics/tutorials/quickstart-python-verify.md
  docs/advanced-analytics/tutorials/sqldev-py3-explore-and-visualize-the-data.md
Labels: Accepted

#677 [LOC] Back-Translation "配信\_元\_データソース id"→"origin_datasource_id"
  docs/relational-databases/system-tables/msmerge-conflict-publication-article-transact-sql.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#681 Typo "&#41"→"&#41;"
  docs/relational-databases/system-tables/msdbms-map-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#683 [LOC] Broken translation "ORACLE ゲートウェイ"→"ORACLE GATEWAY"
  docs/relational-databases/system-stored-procedures/sp-adddistpublisher-transact-sql.md
Labels: Accepted

#684 Typo "MSagent_profiles &#40;&#41; transact-sql"→"MSagent_profiles &#4…
  docs/relational-databases/system-stored-procedures/sp-add-agent-parameter-transact-sql.md
Labels: Accepted

#682 [LOC] Back-Translation "競合"→"Conflicts"
  docs/relational-databases/system-stored-procedures/sp-replmonitorhelpmergesessiondetail-transact-sql.md
Labels: Accepted

#702 [LOC] Back-Translation "**/は\* )。\* /**"→"**/\* \*/**)"
  docs/relational-databases/system-stored-procedures/sp-create-plan-guide-transact-sql.md
Labels: Accepted

#701 [LOC] Back-Translation "整数"→"integer"
  docs/t-sql/data-types/data-type-synonyms-transact-sql.md
Labels: Accepted

#700 [LOC] Back-Translation "句から"→"FROM 句"
  docs/relational-databases/system-functions/freetexttable-transact-sql.md
Labels: Accepted

#699 [LOC] Back-Translation "テキスト"→"text"
  docs/relational-databases/native-client-odbc-results/autotranslation-of-character-data.md
Labels: Accepted

#698 [LOC] Back-Translation "テキスト"→"text"
  docs/t-sql/functions/substring-transact-sql.md
Labels: Accepted

#697 [LOC] Back-Translation "テキスト"→"text"
  docs/relational-databases/native-client-odbc-text-image-columns/managing-text-and-image-columns.md
Labels: Accepted

#696 [LOC] Back-Translation "テキスト"→"text"
  docs/t-sql/data-types/ntext-text-and-image-transact-sql.md
Labels: Accepted

#694 [LOC] Back-Translation "**テキスト**"→"**text**"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-index-operational-stats-transact-sql.md
Labels: Accepted

#693 Typo "sys.dm_os_latch_。stats"→"sys.dm_os_latch_stats"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-file-space-usage-transact-sql.md
Labels: Accepted

#692 [LOC] Back-Translation "**状態**"→"**status**"
  docs/relational-databases/system-dynamic-management-views/sys-dm-io-backup-tapes-transact-sql.md
Labels: Accepted

#691 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql.md
Labels: Accepted

#690 Typo "_exec_query_stats"→"sys.dm_exec_query_stats"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-procedure-stats-transact-sql.md
Labels: Accepted

#689 Typo "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-dynamic-management-views/execution-related-dynamic-management-views-and-functions-transact-sql.md
Labels: Accepted

#688 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-query-plan-transact-sql.md
Labels: Accepted

#695 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-index-physical-stats-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#705 [LOC] Back-Translation "型"→"Type"
  docs/t-sql/statements/set-showplan-all-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#723 [LOC] Back-Translation "**ディストリビューター**"→"**distributor**"
  docs/relational-databases/system-stored-procedures/sp-helpdistributor-transact-sql.md
Labels: Accepted

#722 Typo "10"→10
  docs/relational-databases/system-stored-procedures/sp-mschange-snapshot-agent-properties-transact-sql.md
Labels: Accepted

#721 [LOC] Back-Translation "**能動的**"→"**active**"
  docs/relational-databases/system-stored-procedures/sp-helpdistpublisher-transact-sql.md
Labels: Accepted

#719 [LOC] Back-Translation "**数値 (38)**"→"**numeric(38)**"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-xtp-checkpoint-stats-transact-sql.md
Labels: Accepted

#718 [LOC] Back-Translation "**距離**"→"**Distance**"
  docs/relational-databases/clr-integration-database-objects-user-defined-types/accessing-user-defined-types-retrieving-udt-data.md
Labels: Accepted

#716 Typo "10"→10
  docs/t-sql/functions/cast-and-convert-transact-sql.md
Labels: Accepted

#715 Typo "_db_persisted_sku_features"→"sys.dm_db_persisted_sku_features"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-persisted-sku-features-transact-sql.md
Labels: Accepted

#714 Fixd "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-partition-stats-transact-sql.md
Labels: Accepted

#713 Fixd "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-log-stats-transact-sql.md
Labels: Accepted

#712 Fixd "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-log-space-usage-transact-sql.md
Labels: Accepted

#711 fix "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-log-info-transact-sql.md
Labels: Accepted

#709 Fixed "ssNoversion"→"int"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-fts-index-physical-stats-transact-sql.md
Labels: Accepted

#708 [LOC] Back-Translation "sys.dm_os_tasks と組み合わせます(TRANSACT-SQL)"→"sys.…
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-session-space-usage-transact-sql.md
Labels: Accepted

#707 [LOC] Back-Translation "**数値 (25, 0)**"→"**numeric(25,0)**"
  docs/relational-databases/system-dynamic-management-views/sys-dm-database-replica-states-azure-sql-database.md
Labels: Accepted

#685 [LOC] Broken translation "ORACLE ゲートウェイ"→"ORACLE GATEWAY"
  docs/relational-databases/system-stored-procedures/sp-adddistpublisher-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#703 Suggest to fix 'K-Means'
  docs/advanced-analytics/tutorials/python-clustering-model-build.md
  docs/advanced-analytics/tutorials/python-clustering-model.md
Labels: Accepted, Linguistic Suggestion

#720 [LOC] Back-Translation "チェックポイント&#40;Transact-SQL&#41;"→"CHECKPOINT &…
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-xtp-checkpoint-files-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#727 Typo "transact-sql"→"Transact-SQL"
  docs/relational-databases/system-stored-procedures/sp-adddistributiondb-transact-sql.md
Labels: Accepted

#728 Fixd "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-xtp-gc-cycle-stats-transact-sql.md
Labels: Accepted

#732 Typo "[ &#40;sp_adddistributor transact-sql&#41; ]"→"[sp_adddistribut…
  docs/relational-databases/system-stored-procedures/sp-adddistpublisher-transact-sql.md
Labels: Accepted

#731 Typo "transact-sql"→"Transact-SQL"
  docs/relational-databases/system-stored-procedures/sp-add-agent-profile-transact-sql.md
Labels: Accepted

#737 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mssubscriptions-transact-sql.md
Labels: Accepted

#736 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msdistributor-transact-sql.md
Labels: Accepted

#735 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/msdistribution-status-transact-sql.md
Labels: Accepted

#734 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/sysdatatypemappings-transact-sql.md
Labels: Accepted

#733 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspub-identity-range-transact-sql.md
Labels: Accepted

#739 [LOC] Back-Translation "**図形**"→"**"SHAPE**""
  docs/dmx/source-data-query-shape.md
Labels: Accepted

#738 [LOC] Back-Translation "[バイナリ]"→"binary"
  docs/relational-databases/system-views/ihextendedsubscriptionview-transact-sql.md
Labels: Accepted

#742 [LOC] Back-Translation "|**フィルター (filter)**|"→"|**filter**|"
  docs/relational-databases/system-views/sysextendedarticlesview-transact-sql.md
Labels: Accepted

#741 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/sysmergearticlecolumns-transact-sql.md
Labels: Accepted

#740 [LOC] Back-Translation "|**ホスト名**|"→"|**hostname**|"
  docs/relational-databases/system-stored-procedures/sp-who-transact-sql.md
Labels: Accepted

#745 Back-Translation "|**フィルター (filter)**|"→"|**filter**|"
  docs/relational-databases/system-views/sysarticles-system-view-transact-sql.md
Labels: Accepted

#744 Fixed "MS"→"MSSQLSERVER"
  docs/relational-databases/system-stored-procedures/sp-helpdatatypemap-transact-sql.md
Labels: Accepted

#743 [LOC] Back-Translation "|**能動的**|"→"|**active**|"
  docs/relational-databases/system-stored-procedures/sp-changedistpublisher-transact-sql.md
Labels: Accepted

#730 Suggest to fix 'key=val'
  docs/big-data-cluster/spark-hive-tools-vscode.md
Labels: Accepted, Linguistic Suggestion

#748 [LOC] Back-Translation "名"→"hostname"
  docs/relational-databases/system-stored-procedures/sp-helpsubscription-properties-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#747 [LOC] Back-Translation "サブスクライバー"→"subscriber"
  docs/relational-databases/system-stored-procedures/sp-helpsubscription-transact-sql.md
Labels: Accepted

#753 [LOC] Back-Translation "フィールド"→"Field"
  docs/ado/guide/appendixes/microsoft-cursor-service-for-ole-db-ado-service-component.md
Labels: Accepted

#751 [LOC] Back-Translation "有効桁数"→"precision"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-describe-first-result-set-transact-sql.md
Labels: Accepted

#750 [LOC] Back-Translation "**さん**"→"**tran**"
  docs/relational-databases/system-stored-procedures/sp-removedbreplication-transact-sql.md
Labels: Accepted

#754 [LOC] Back-Translation "バックアップを使用した初期化"→"initialize with backup"
  docs/relational-databases/system-stored-procedures/sp-addsubscription-transact-sql.md
Labels: Accepted

#749 Fix 'K-Means'
  docs/advanced-analytics/tutorials/python-clustering-model-build.md
  docs/advanced-analytics/tutorials/sql-server-python-tutorials.md
Labels: Accepted, Linguistic Suggestion

#755 Fixd "[ALTER ASSEMBLY &#40Transact-SQL&#41;]"→"[ALTER ASSEMBLY &#40;T…
  docs/relational-databases/clr-integration-database-objects-user-defined-types/registering-user-defined-types-in-sql-server.md
Labels: Accepted

#758 [LOC] Back-Translation "**場所**結合"→"**WHERE**結合"
  docs/relational-databases/system-tables/mssubscription-properties-transact-sql.md
Labels: Accepted

#757 Typo "**@publication**"→"**\@publication**"
  docs/relational-databases/replication/delete-a-push-subscription.md
Labels: Accepted

#759 [LOC] Back-Translation "**場所**句"→"**WHERE**句"
  docs/odbc/reference/develop-app/optimistic-concurrency.md
Labels: Accepted

#763 [LOC] Back-Translation "**[バイナリ]**"→"**binary**"
  docs/relational-databases/system-views/sysextendedarticlesview-transact-sql.md
Labels: Accepted

#761 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mslogreader-history-transact-sql.md
Labels: Accepted

#762 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/syssubscriptions-system-view-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#760 [LOC] Broken translation "the same result set definition"→"同じ結果セット定義"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-describe-first-result-set-for-object-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#756 Fix and improve ROWVERSION
  docs/t-sql/data-types/rowversion-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#764 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msrepl-version-transact-sql.md
Labels: Accepted

#768 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/sysmergepartitioninfoview-transact-sql.md
Labels: Accepted

#767 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/sysmergeextendedarticlesview-transact-sql.md
Labels: Accepted

#766 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/sysextendedarticlesview-transact-sql.md
Labels: Accepted

#765 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/syssubscriptions-system-view-transact-sql.md
Labels: Accepted

#770 [LOC] Back-Translation "レポート"→"Report"
  docs/relational-databases/system-stored-procedures/sp-change-users-login-transact-sql.md
Labels: Accepted

#752 Typo "transact-sql"→"Transact-SQL"
  docs/relational-databases/system-stored-procedures/sp-helpsubscription-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#746 [LOC] Back-Translation "**ディストリビューター**"→"**distributor**"
  docs/relational-databases/system-stored-procedures/sp-helpdistributor-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#772 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/syspublications-system-view-transact-sql.md
Labels: Accepted

#773 Fix replacees
  docs/big-data-cluster/big-data-cluster-overview.md
  docs/big-data-cluster/deploy-big-data-tools.md
  docs/big-data-cluster/deploy-install-azdata-linux-package.md
  docs/big-data-cluster/deployment-script-single-node-kubeadm.md
  docs/relational-databases/system-dynamic-management-views/sql-server-operating-system-related-dynamic-management-views-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-os-enumerate-fixed-drives.md
Labels: Accepted
