Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2019-06, with the labels that each got.

#264 Suggest to improve translations
  docs/relational-databases/polybase/polybase-t-sql-objects.md
Labels: Accepted, Linguistic Suggestion

#270 fix "#40";"データベース エンジン"&"#41 です。"→"(データベース エンジン)"
  docs/t-sql/data-types/getancestor-database-engine.md
Labels: Accepted

#271 Fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/data-type-functions-transact-sql.md
Labels: In Progress

#272 [LOC] fixed inappropriate japanese
  docs/t-sql/functions/security-functions-transact-sql.md
Labels: Accepted

#273 fixed "[SYSTEM_USER (&) #40 です。TRANSACT-SQL と #41 です。]"→"[SYSTEM_USER…
  docs/t-sql/functions/security-functions-transact-sql.md
Labels: In Progress, Linguistic Suggestion

#274 [LOC] Back-Translation "ブール値"→"Boolean"
  docs/t-sql/data-types/data-type-conversion-database-engine.md
Labels: Accepted

#275 fix "[暗号化機能と #40 です。TRANSACT-SQL と #41;"→"暗号化関数&#40;Transact-SQL&#41;"
  docs/t-sql/functions/security-functions-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#276 [LOC] Back-Translation "ユーザー名"→"USER_NAME"
  docs/t-sql/functions/current-user-transact-sql.md
Labels: Accepted

#277 [LOC] fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/user-name-transact-sql.md
Labels: Accepted

#279 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/symkeyproperty-transact-sql.md
Labels: Accepted

#280 [LOC] Back-Translation "部分文字列"→"SUBSTRING"
  docs/t-sql/data-types/ntext-text-and-image-transact-sql.md
Labels: Accepted

#281 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/verifysignedbyasymkey-transact-sql.md
Labels: Accepted

#282 [LOC] Back-Translation "開く"→"OPEN"
  docs/t-sql/functions/cursor-rows-transact-sql.md
Labels: Accepted

#283 [LOC] Back-Translation "フェッチ"→"FETCH"
  docs/t-sql/language-elements/open-transact-sql.md
Labels: Accepted

#287 [LOC] Back-Translation "書き込み"→"Write"
  docs/t-sql/data-types/read-database-engine.md
Labels: In Progress

#286 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/filegroup-id-transact-sql.md
Labels: In Progress

#285 fix "(&) #40";"データベース エンジン"&"#41;"→"&#40;データベース エンジン&#41;"
  docs/t-sql/functions/string-functions-transact-sql.md
Labels: In Progress

#284 fix "[SET TEXTSIZE] (&) #40 です。TRANSACT-SQL と #41 です。"→"SET TEXTSIZE …
  docs/t-sql/data-types/ntext-text-and-image-transact-sql.md
Labels: Accepted

#289 [LOC] fix "アクセスを許可します"→"アクセス権の付与"
  docs/analysis-services/multidimensional-models/roles-and-permissions-analysis-services.md
Labels: Accepted

#290 fix "および #40 です。TRANSACT-SQL と #41;."→"&#40;Transact-SQL&#41;"
  docs/t-sql/statements/bulk-insert-transact-sql.md
Labels: Accepted

#291 fix "OPENQUERY & #40;DMX& #41;"→"OPENQUERY &#40;DMX&#41;"
  docs/analysis-services/multidimensional-models/grant-permissions-on-data-mining-structures-and-models-analysis-services.md
Labels: Accepted

#292 fix "と #40 です。Analysis Services & #41;"→" &#40;Analysis Services&#41;"
  docs/analysis-services/multidimensional-models/mdx/mdx-data-modification-modifying-data.md
Labels: Accepted

#293 fix "(& a) #40 です。TRANSACT-SQL と #41;"→" &#40;Transact-SQL&#41;"
  docs/t-sql/functions/min-active-rowversion-transact-sql.md
Labels: Accepted

#295 fix "& #40 です。TRANSACT-SQL と #41;"→"&#40;Transact-SQL&#41;"
  docs/t-sql/data-types/datetime-transact-sql.md
Labels: Accepted

#294 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/data-types/date-and-time-types.md
Labels: Accepted
