Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2019-10, with the labels that each got.

#776 [LOC] Back-Translation "場所"→"WHERE"
  docs/odbc/reference/syntax/sqlexecdirect-function.md
Labels: Accepted

#775 [LOC] Back-Translation "場所"→"WHERE"
  docs/odbc/reference/syntax/sqlspecialcolumns-function.md
Labels: Accepted

#774 [LOC] Back-Translation "場所"→"WHERE"
  docs/odbc/reference/syntax/sqlsetdescfield-function.md
Labels: Accepted

#769 Improve translations
  docs/advanced-analytics/tutorials/quickstart-python-create-script.md
  docs/advanced-analytics/tutorials/quickstart-r-create-script.md
Labels: Accepted, Linguistic Suggestion

#778 Typo "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-views/sysdatatypemappings-transact-sql.md
Labels: Accepted

#777 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msdistributiondbs-transact-sql.md
Labels: Accepted

#780 [LOC] Back-Translation "**[バイナリ]**"→"**binary**"
  docs/relational-databases/system-views/systranschemas-transact-sql.md
Labels: Accepted

#779 Fixd "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/sysmergeextendedarticlesview-transact-sql.md
Labels: Accepted

#784 Typo "**@publication=**"→"**\@publication=**"
  docs/relational-databases/system-stored-procedures/sp-validatemergepublication-transact-sql.md
Labels: Accepted

#782 [LOC]Back-Translation "投稿"→"publish"
  docs/relational-databases/system-stored-procedures/sp-helpreplicationdboption-transact-sql.md
Labels: Accepted

#783 [LOC] Back-Translation "型"→”Type”
  docs/relational-databases/system-stored-procedures/sp-help-agent-profile-transact-sql.md
Labels: Accepted

#785 Typo "**@agent_type=**"→"**\@agent_type=**"
  docs/relational-databases/system-stored-procedures/sp-update-agent-profile-transact-sql.md
Labels: Accepted

#786 [LOC]fixed inappropriate japanese "場合、pending_deletes"→"pending_deletes"
  docs/relational-databases/system-stored-procedures/sp-showpendingchanges-transact-sql.md
Labels: Accepted

#787 [LOC] Back-Translation "元の XACT_SEQNO"→”ORIGINAL XACT_SEQNO”
  docs/relational-databases/system-stored-procedures/sp-setsubscriptionxactseqno-transact-sql.md
Labels: Accepted

#791 Fix 'no__t'
  docs/advanced-analytics/tutorials/quickstart-python-functions.md
Labels: In Progress

#792 [LOC] Back-Translation "**イミディ エイト**"→"**immediate**"
  docs/relational-databases/system-stored-procedures/sp-setreplfailovermode-transact-sql.md
Labels: Accepted

#793 [LOC] Back-Translation "**型**"→"**Type**"
  docs/relational-databases/system-stored-procedures/sp-enumdsn-transact-sql.md
Labels: Accepted

#795 Typo "**_ _ $reason_text**"→"**__$reason_text**"
  docs/relational-databases/system-tables/conflict-schema-table-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#794 Typo **&#42;&#42;&#42;"&#42;"→"**&#42;&#42;&#42;&#42;&#42;&#42;**"
  docs/relational-databases/system-stored-procedures/sp-helpsubscription-transact-sql.md
Labels: Accepted

#796 Fixd "& #40 を参照してください。TRANSACT-SQL と #41 です"→" &#40;Transact-SQL&#41;…
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-describe-first-result-set-for-object-transact-sql.md
Labels: In Progress

#797 [LOC] Back-Translation "系列"→"lineage"
  docs/relational-databases/system-tables/msmerge-errorlineage-transact-sql.md
Labels: In Progress

#798 Typo "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-views/sysmergepartitioninfoview-transact-sql.md
Labels: Accepted

#814 invalid translation
  docs/relational-databases/tables/tables.md
Labels: In Progress

#808 [LOC] Translation "Peer-to-Peer Transactional Replication"→"ピア ツー ピア …
  docs/relational-databases/replication/transactional/updatable-subscriptions-for-transactional-replication.md
Labels: Accepted, Linguistic Suggestion

#807 [LOC] Translation "Publishing Stored Procedure Execution in Transacti…
  docs/relational-databases/replication/transactional/article-options-for-transactional-replication.md
Labels: Accepted, Linguistic Suggestion

#806 [LOC] Translation "Peer-to-Peer Transactional Replication"→"ピア ツー ピア …
  docs/relational-databases/replication/transactional/transactional-replication.md
Labels: Accepted, Linguistic Suggestion

#813 [LOC] Translation "Peer-to-Peer Transactional Replication"→"ピア ツー ピア …
  docs/relational-databases/replication/transactional/updatable-subscriptions-for-transactional-replication.md
Labels: Accepted, Linguistic Suggestion

#799 Fixed "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-errorlineage-transact-sql.md
Labels: In Progress, Linguistic Suggestion

#800 Fixed "@loopback_detection"→"ピア ツー ピア トランザクション レプリケーション"
  docs/relational-databases/replication/configure-peer-to-peer-topology-wizard.md
Labels: Accepted, Linguistic Suggestion

#803 Fixed "@loopback_detection"→"ピア ツー ピア トランザクション レプリケーション"
  docs/relational-databases/replication/log-reader-agent-security-peer-to-peer-replication.md
Labels: Accepted, Linguistic Suggestion

#802 Fixed "@loopback_detection"→"ピア ツー ピア トランザクション レプリケーション"
  docs/relational-databases/replication/configure-topology-peer-to-peer-replication.md
Labels: Accepted, Linguistic Suggestion

#801 Fixed "@loopback_detection"→"ピア ツー ピア トランザクション レプリケーション"
  docs/relational-databases/replication/publication-peer-to-peer-replication.md
Labels: Accepted, Linguistic Suggestion

#805 Fixed "@loopback_detection"→"ピア ツー ピア トランザクション レプリケーション"
  docs/relational-databases/replication/new-peer-initialization-peer-to-peer-replication.md
Labels: Accepted, Linguistic Suggestion

#804 Fixed "@loopback_detection"→"ピア ツー ピア トランザクション レプリケーション"
  docs/relational-databases/replication/distribution-agent-security-peer-to-peer-replication.md
Labels: Accepted, Linguistic Suggestion

#812 Fixed "@loopback_detection"→"ピア ツー ピア トランザクション レプリケーション"
  docs/relational-databases/replication/transactional/bidirectional-transactional-replication.md
Labels: Accepted, Linguistic Suggestion

#811 Fixed "@loopback_detection"→"ピア ツー ピア トランザクション レプリケーション"
  docs/relational-databases/replication/transactional/peer-to-peer-conflict-detection-in-peer-to-peer-replication.md
Labels: Accepted, Linguistic Suggestion

#815 [LOC]Broken link "の"
  docs/relational-databases/replication/view-data-conflicts-for-transactional-publications-sql-server-management-studio.md
Labels: Accepted, Linguistic Suggestion

#816 [LOC] Back-Translation "[バイナリ]"→"binary"
  docs/ssma/sybase/project-settings-type-mapping-sybasetosql.md
Labels: In Progress

#817 Typo "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-stored-procedures/sp-dropextendedproperty-transact-sql.md
Labels: In Progress

#819 Typo "transact-sql"→"Transact-SQL"
  docs/relational-databases/system-views/sysmergeextendedarticlesview-transact-sql.md
Labels: In Progress

#820 Typo "@dotnet_assembly_name"→"dotnet_assembly_name"
  docs/relational-databases/system-stored-procedures/sp-enumcustomresolvers-transact-sql.md
Labels: In Progress

#821 [LOC] Back-Translation "**される**"→"**schemaguid**"
  docs/relational-databases/system-stored-procedures/sp-enumeratependingschemachanges-transact-sql.md
Labels: In Progress

#822 [LOC] Back-Translation "インストールされています。"→"linstalled"
  docs/relational-databases/system-stored-procedures/sp-get-distributor-transact-sql.md
Labels: In Progress

#823 [LOC] Back-Translation "|**操作**|"→"|**Action**|"
  docs/relational-databases/system-stored-procedures/sp-getqueuedrows-transact-sql.md
Labels: In Progress

#824 [LOC] Back-Translation "|**ログイン**|"→"|**Loginname**|"
  docs/relational-databases/system-stored-procedures/sp-help-publication-access-transact-sql.md
Labels: In Progress

#825 [LOC] Back-Translation "|**アーティクル id**|"→"|**article id**|"
  docs/relational-databases/system-stored-procedures/sp-helparticle-transact-sql.md
Labels: In Progress

#826 [LOC] Back-Translation "|**列 id**|"→"|**column id**|"
  docs/relational-databases/system-stored-procedures/sp-helparticlecolumns-transact-sql.md
Labels: In Progress

#827 [LOC] Back-Translation "|**履歴の保有期間**|"→"|**history retention**|"
  docs/relational-databases/system-stored-procedures/sp-helpdistributiondb-transact-sql.md
Labels: In Progress

#818 [LOC]Back-Translation "|**データベース名**|"→"|**DBName**|"
  docs/relational-databases/system-stored-procedures/sp-helplogins-transact-sql.md
Labels: Accepted

#834 [LOC] Back-Translation "|**ピア**|"→"|**peer**|"
  docs/relational-databases/system-stored-procedures/sp-helppeerresponses-transact-sql.md
Labels: Accepted

#833 [LOC] Back-Translation "|**パブリケーション**|"→"|**publication**|"
  docs/relational-databases/system-stored-procedures/sp-helppeerrequests-transact-sql.md
Labels: Accepted

#832 [LOC] Back-Translation "|**パブリケーション**|"→"|**publication**|"
  docs/relational-databases/system-stored-procedures/sp-helpmergepullsubscription-transact-sql.md
Labels: Accepted

#831 [LOC] Back-Translation "|**結合アーティクル名**|"→"|**join article name**|"
  docs/relational-databases/system-stored-procedures/sp-helpmergefilter-transact-sql.md
Labels: Accepted

#830 [LOC] Back-Translation "|**公開**|"→"**published**|"
  docs/relational-databases/system-stored-procedures/sp-helpmergearticlecolumn-transact-sql.md
Labels: Accepted

#835 [LOC] Back-Translation "|ステータス|"→"|status|"
  docs/relational-databases/system-stored-procedures/sp-helppublication-transact-sql.md
Labels: Accepted

#836 [LOC] Back-Translation "|**パブリッシャー**|"→"|**publisher**|"
  docs/relational-databases/system-stored-procedures/sp-helppullsubscription-transact-sql.md
Labels: Accepted

#838 [LOC] Back-Translation "|**サブスクライバー**|"→"|**subscriber**|"
  docs/relational-databases/system-stored-procedures/sp-helptracertokenhistory-transact-sql.md
Labels: In Progress
