Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2019-12, with the labels that each got.

#906 [LOC]Back-Translation "継続的です"→"continuous"
  docs/relational-databases/system-stored-procedures/sys-sp-cdc-help-jobs-transact-sql.md
Labels: Accepted

#911 [LOC] Back-Translation "|ソース テーブル|"→"|source_table|"
  docs/relational-databases/system-stored-procedures/sys-sp-cdc-help-change-data-capture-transact-sql.md
Labels: Accepted

#910 [LOC] Back-Translation "|ソース テーブル|"→"|source_table|"
  docs/relational-databases/system-stored-procedures/sys-sp-cdc-get-ddl-history-transact-sql.md
Labels: Accepted

#909 [LOC] Back-Translation "|ソース テーブル|"→"|source_table|"
  docs/relational-databases/system-stored-procedures/sys-sp-cdc-get-captured-columns-transact-sql.md
Labels: Accepted

#908 [LOC] Back-Translation "**_ _ $操作**"→"**__$operation**"
  docs/relational-databases/system-stored-procedures/sys-sp-cdc-enable-table-transact-sql.md
Labels: Accepted

#915 [LOC] Back-Translation "|**フォルダー名**|"→"|**foldername**|"
  docs/relational-databases/system-tables/sysssispackagefolders-transact-sql.md
Labels: Accepted

#914 [LOC] Back-Translation "|イベント|"→"|source_table|"
  docs/relational-databases/system-tables/sysssislog-transact-sql.md
Labels: Accepted

#913 [LOC] Back-Translation "|**所有者**|"→"|**owner**|"
  docs/relational-databases/system-tables/sysdbmaintplans-transact-sql.md
Labels: Accepted

#912 [LOC] Back-Translation "|**一意識別子**|"→"|**Uniqueidentifier**|"
  docs/relational-databases/system-tables/sysdbmaintplan-databases-transact-sql.md
Labels: Accepted

#902 [LOC] Back-Translation "*カテゴリ*"→"*category*"
  docs/relational-databases/system-stored-procedures/sp-update-operator-transact-sql.md
Labels: Accepted

#905 Typo "|TINYINT|"→"|tinyint|"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-column-store-row-group-physical-stats-transact-sql.md
Labels: In Progress, Linguistic Suggestion, Source Issue

#901 [LOC] Back-Translation "拇印"→"thumbprint"
  docs/relational-databases/system-functions/sys-fn-check-object-signatures-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#916 [LOC] Back-Translation "必須"→"Required"
  docs/relational-databases/system-tables/data-tier-application-tables-sysdac-history-internal.md
Labels: Accepted

#907 [LOC] Back-Translation "削除のしきい値"→"delete threshold"
  docs/relational-databases/system-stored-procedures/sys-sp-cdc-cleanup-change-table-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#917 Fixed translation mistakes.
  docs/connect/node-js/step-3-proof-of-concept-connecting-to-sql-using-node-js.md
Labels: Accepted, Linguistic Suggestion

#918 Fixed "#40;SQL Server&#41;"→"&#40;SQL Server&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-hadr-instance-node-map-transact-sql.md
Labels: Accepted

#920 [LOC] Translation "Configure an Oracle Publisher"→"Oracle パブリッシャーの構成"
  docs/relational-databases/replication/non-sql/oracle-publishing-overview.md
Labels: Accepted, Linguistic Suggestion

#928 [LOC] Translation "Configure an Oracle Publisher"→"Oracle パブリッシャーの構成"
  docs/relational-databases/replication/non-sql/objects-created-on-the-oracle-publisher.md
Labels: Accepted, Linguistic Suggestion

#923 [LOC] Translation "Configure an Oracle Publisher"→"Oracle パブリッシャーの構成"
  docs/relational-databases/replication/non-sql/glossary-of-terms-for-oracle-publishing.md
Labels: Accepted, Linguistic Suggestion

#927 [LOC] Translation "Scripting Replication"→"レプリケーションのスクリプト作成"
  docs/relational-databases/replication/non-sql/backup-and-restore-for-oracle-publishers.md
Labels: Accepted, Linguistic Suggestion
