Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2019-11, with the labels that each got.

#841 'Getting started with'
  docs/connect/toc.yml
Labels: Accepted, Linguistic Suggestion

#848 [LOC] Back-Translation "|**パブリッシャー**|"→"|**publisher**|"
  docs/relational-databases/system-stored-procedures/sp-addmergepublication-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#850 Typo "|"**10**"|"→"|**10**|"
  docs/relational-databases/system-stored-procedures/sp-addmergepushsubscription-agent-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#846 Fix dynamic management views
  docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-nodes-exec-query-plan-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-nodes-exec-query-profiles-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-nodes-exec-query-statistics-xml-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-nodes-exec-sql-text-transact-sql.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-pdw-nodes-exec-text-query-plan-transact-sql.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#856 update step title that over-translated module name
  docs/connect/node-js/step-1-configure-development-environment-for-node-js-development.md
Labels: Accepted, Linguistic Suggestion

#855 Fixed "[検出およびマージ レプリケーションの競合を解決します。]"→"[マージ レプリケーションの詳細 - 競合の検出および解決]"
  docs/relational-databases/system-stored-procedures/sp-showrowreplicainfo-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#862 [LOC]Back-Translation "|**拇印**|"→"|**thumbprint**|"
  docs/relational-databases/system-catalog-views/sys-key-encryptions-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#863 [LOC]Back-Translation "**データベース**"→"**database**"
  docs/relational-databases/system-stored-procedures/sp-adddistributiondb-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#840 Improve translation
  docs/connect/ado-net/sqlclient-driver-support-lifecycle.md
Labels: Accepted, Linguistic Suggestion

#861 Update hardware-and-software-requirements-for-installing-sql-server.md
  docs/sql-server/install/hardware-and-software-requirements-for-installing-sql-server.md
Labels: Accepted, Linguistic Suggestion

#842 'NONE', 'SWITCH'
  docs/t-sql/statements/alter-table-index-option-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#845 Typo "*@dotnet_class_name*"→"*dotnet_class_name*"
  docs/relational-databases/system-stored-procedures/sp-lookupcustomresolver-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#847 [LOC] Back-Translation "|**テーブル**(既定値)|"→"|**table** (既定値)|"
  docs/relational-databases/system-stored-procedures/sp-addmergearticle-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#849 [LOC] Back-Translation "**自動**"→"**automatic**"
  docs/relational-databases/system-stored-procedures/sp-addmergepullsubscription-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#865 語順の修正
  docs/sql-server/install/security-considerations-for-a-sql-server-installation.md
Labels: Accepted, Linguistic Suggestion

#864 [LOC]Back-Translation "|**ディストリビューター**|"→"|**distributor**|"
  docs/relational-databases/system-stored-procedures/sp-changereplicationserverpasswords-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#868 Fix a view name
  docs/relational-databases/system-catalog-views/sys-workload-management-workload-groups-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#869 [LOC]Back-Translation "|**継続的です**|"→"|**continuous**|"
  docs/relational-databases/system-tables/dbo-cdc-jobs-transact-sql.md
Labels: Accepted

#870 Fixed inappropriate japanese "cdc です。"→"cdc."
  docs/relational-databases/system-tables/cdc-lsn-time-mapping-transact-sql.md
Labels: Accepted

#851 [LOC] Back-Translation "|**すばやい**|"→"|**immediate**|"
  docs/relational-databases/system-stored-procedures/sp-helpreplfailovermode-transact-sql.md
Labels: Linguistic Suggestion, Partially Accepted

#853 [LOC] Back-Translation "パブリケーション"→"publication"
  docs/relational-databases/system-stored-procedures/sp-validatemergesubscription-transact-sql.md
Labels: Linguistic Suggestion, Partially Accepted

#854 Typo "[ **\@publication=** ]"→"[ @publication = ]"
  docs/relational-databases/system-stored-procedures/sp-validatemergepublication-transact-sql.md
Labels: Linguistic Suggestion, Partially Accepted

#857 [LOC] Back-Translation "|**パブリッシャー**|"→"|**publisher**|"
  docs/relational-databases/system-stored-procedures/sp-replmonitorhelppublisher-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#858 [LOC] Back-Translation "|**の場合は、**|"→"|**distributionagentid**|"
  docs/relational-databases/system-stored-procedures/sp-replmonitorhelpsubscription-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#859 Typo " **[@queuetype=** ]"→"`[ @queuetype = ]"
  docs/relational-databases/system-stored-procedures/sp-replqueuemonitor-transact-sql.md
Labels: Linguistic Suggestion, Partially Accepted

#860 [LOC] Back-Translation "|**スキーマ名**|"→"|**schemaname**|"
  docs/relational-databases/system-stored-procedures/sp-schemafilter-transact-sql.md
Labels: Linguistic Suggestion, Partially Accepted

#867 機械翻訳の修正
  docs/relational-databases/administer-multiple-servers-using-central-management-servers.md
Labels: Accepted, Linguistic Suggestion

#866 機械翻訳の修正
  docs/big-data-cluster/big-data-cluster-overview.md
Labels: Accepted, Linguistic Suggestion

#872 typo 同一の記載削除
  docs/relational-databases/databases/manage-metadata-when-making-a-database-available-on-another-server.md
Labels: Accepted, Source Issue

#873 Fix 'extensions'
  docs/language-extensions/concepts/extensibility-framework.md
Labels: Accepted, Linguistic Suggestion

#875 [LOC]Back-Translation "なし"→"NONE"
  docs/t-sql/statements/alter-availability-group-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#874 [LOC]Back-Translation "なし"→"NONE"
  docs/t-sql/statements/alter-message-type-transact-sql.md
Labels: Accepted

#876 [LOC]Translation "String"→"文字列"
  docs/t-sql/statements/alter-fulltext-stoplist-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#877 機械翻訳の修正
  docs/sql-server/install/work-with-multiple-versions-and-instances-of-sql-server.md
Labels: Accepted, Linguistic Suggestion

#879 [LOC] Back-Translation "スキーマ比較"→"Schema Component"
  docs/t-sql/statements/alter-xml-schema-collection-transact-sql.md
Labels: Accepted

#880 [LOC] Back-Translation "サイト"→"site"
  docs/relational-databases/system-catalog-views/sys-http-endpoints-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#881 [LOC] Back-Translation "名前空間"→"namespace"
  docs/relational-databases/system-catalog-views/sys-endpoint-webmethods-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#882 [LOC] Back-Translation "プロトコル"→"protocol"
  docs/relational-databases/system-catalog-views/sys-endpoints-transact-sql.md
Labels: Accepted

#883 [LOC] Back-Translation "型"→"type"
  docs/relational-databases/system-catalog-views/sys-database-files-transact-sql.md
Labels: Accepted

#884 [LOC] Back-Translation "モジュール"→"module"
  docs/relational-databases/system-catalog-views/sys-database-event-session-targets-azure-sql-database.md
Labels: Accepted

#885 Typo "NAME"→"name"
  docs/relational-databases/system-catalog-views/sys-database-event-session-fields-azure-sql-database.md
Labels: Accepted

#886 [LOC] Back-Translation "述語"→"predicate"
  docs/relational-databases/system-catalog-views/sys-database-event-session-events-azure-sql-database.md
Labels: Accepted

#887 [LOC] Back-Translation "モジュール"→"module"
  docs/relational-databases/system-catalog-views/sys-database-event-session-actions-azure-sql-database.md
Labels: Accepted

#888 [LOC] Back-Translation "モジュール"→"module"
  docs/relational-databases/system-catalog-views/sys-server-event-session-actions-transact-sql.md
Labels: Accepted

#889 [LOC] Back-Translation "述語"→"predicate"
  docs/relational-databases/system-catalog-views/sys-server-event-session-events-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#890 Typo "NAME"→"name"
  docs/relational-databases/system-catalog-views/sys-server-event-session-fields-transact-sql.md
Labels: Accepted

#894 [LOC] Back-Translation "モジュール"→"module"
  docs/relational-databases/system-catalog-views/sys-server-event-session-targets-transact-sql.md
Labels: Accepted

#895 [LOC] Back-Translation "有効桁数"→"precision"
  docs/relational-databases/system-catalog-views/sys-types-transact-sql.md
Labels: Accepted

#896 [LOC] Back-Translation "拇印"→"thumbprint"
  docs/relational-databases/system-catalog-views/sys-asymmetric-keys-transact-sql.md
Labels: Accepted

#871 Fix view names
  docs/relational-databases/system-dynamic-management-views/sys-dm-column-encryption-enclave.md
  docs/relational-databases/system-dynamic-management-views/sys-dm-workload-management-workload-group-stats-transact-sql.md
Labels: In Progress

#893 [LOC]Fixed inappropriate japanese "Filetable を管理します。"→"FileTable の管理"
  docs/relational-databases/system-catalog-views/sys-filetables-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#898 [LOC] Back-Translation "拇印"→"thumbprint"
  docs/relational-databases/system-catalog-views/sys-certificates-transact-sql.md
Labels: Linguistic Suggestion, Partially Accepted

#899 [LOC] Back-Translation "拇印"→"thumbprint"
  docs/relational-databases/system-catalog-views/sys-crypt-properties-transact-sql.md
Labels: In Progress

#900 [LOC] Back-Translation "[位置]"→"Position"
  docs/t-sql/statements/restore-statements-headeronly-transact-sql.md
Labels: In Progress

#897 [LOC] Back-Translation "セキュリティカタログビュー"→"Security Catalog Views"
  docs/relational-databases/system-catalog-views/security-catalog-views-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#904 [LOC]Back-Translation "|**継続的です**|"→"|**continuous**|"
  docs/relational-databases/system-tables/dbo-cdc-jobs-transact-sql.md
Labels: Accepted, Technical Issue

#903 Fixd "**INFORMATION_SCHEMA** 。_view_name_"→"**INFORMATION_SCHEMA.**_v…
  docs/relational-databases/system-information-schema-views/key-column-usage-transact-sql.md
Labels: Accepted
