Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2019-07, with the labels that each got.

#296 [LOC] Back-Translation "時間" → "time"
  docs/t-sql/data-types/datetime-transact-sql.md
Labels: Accepted

#298 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/asymkeyproperty-transact-sql.md
Labels: Accepted

#299 [LOC] Back-Translation "証明書を変更します"→"ALTER CERTIFICATE"
  docs/t-sql/functions/certproperty-transact-sql.md
Labels: Accepted

#300 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/asymkey-id-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#311 fix "フェッチ (&) #40 です。TRANSACT-SQL と #41 です。"→"FETCH &#40;Transact-SQL…
  docs/t-sql/functions/fetch-status-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#310 fix "ASYMKEY_ID (&) #40 です。TRANSACT-SQL と #41 です。"→"ASYMKEY_ID &#40;T…
  docs/t-sql/functions/signbyasymkey-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#309 fix "sys.symmetric_keys (&) #40 です。TRANSACT-SQL と #41 です。"→"sys.symme…
  docs/t-sql/functions/key-name-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#308 fix "KEY_GUID (&) #40 です。TRANSACT-SQL と #41 です。"→"KEY_GUID &#40;Trans…
  docs/t-sql/functions/key-id-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#307 fix "sys.symmetric_keys (&) #40 です。TRANSACT-SQL と #41 です。"→"sys.symme…
  docs/t-sql/functions/key-guid-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#306 fix "sys.fn_check_object_signatures (&) #40 です。TRANSACT-SQL と #41 です。…
  docs/t-sql/functions/is-objectsigned-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#305 fix "チェックサム (&) #40 です。TRANSACT-SQL と #41 です。"→"CHECKSUM &#40;Transac…
  docs/t-sql/functions/hashbytes-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#304 fix "DECRYPTBYPASSPHRASE (&) #40 です。TRANSACT-SQL と #41 です。"→"DECRYPTB…
  docs/t-sql/functions/encryptbypassphrase-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#303 fix "HASHBYTES (&) #40 です。TRANSACT-SQL と #41 です。"→"HASHBYTES &#40;Tra…
  docs/t-sql/functions/encryptbykey-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#302 fix "RAND (&) #40 です。TRANSACT-SQL と #41 です。"→"RAND &#40;Transact-SQL&…
  docs/t-sql/functions/crypt-gen-random-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#313 fix "言語を設定する (&) #40 です。TRANSACT-SQL と #41 です。"→"SET LANGUAGE &#40;Tr…
  docs/t-sql/functions/langid-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#312 fix "#40; を解析する (& a)TRANSACT-SQL と #41 です。"→"PARSE &#40;Transact-SQL…
  docs/t-sql/functions/conversion-functions-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#324 fix "CUME_DIST (&) #40 です。TRANSACT-SQL と #41 です。"→"CUME_DIST &#40;Tra…
  docs/t-sql/functions/percent-rank-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#323 fix "PERCENTILE_CONT と #40 です。TRANSACT-SQL と #41 です。"→"PERCENTILE_CON…
  docs/t-sql/functions/percentile-disc-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#322 fix "PERCENTILE_DISC (&) #40 です。TRANSACT-SQL と #41 です。"→"PERCENTILE_D…
  docs/t-sql/functions/percentile-cont-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#321 fix "間隔 (&) #40 です。TRANSACT-SQL と #41 です。"→"LAG &#40;Transact-SQL&#41;"
  docs/t-sql/functions/lead-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#320 fix "潜在顧客と #40 です。TRANSACT-SQL と #41 です。"→"LEAD &#40;Transact-SQL&#41;"
  docs/t-sql/functions/lag-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#319 fix "PERCENT_RANK (&) #40 です。TRANSACT-SQL と #41 です。"→"PERCENT_RANK &#…
  docs/t-sql/functions/cume-dist-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#317 fix "CUME_DIST (&) #40 です。TRANSACT-SQL と #41 です。"→"CUME_DIST &#40;Tra…
  docs/t-sql/functions/analytic-functions-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#316 fix "[SET TEXTSIZE] (&) #40 です。TRANSACT-SQL と #41 です。"→"SET TEXTSIZE …
  docs/t-sql/functions/textsize-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#315 fix "10 進数の数値と #40 です。TRANSACT-SQL と #41 です。"→"decimal 型と numeric 型 &…
  docs/t-sql/functions/max-precision-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#345 fix "[集計関数 (&) #40 です。TRANSACT-SQL と #41 です。]"→"[集計関数 &#40;Transact-S…
  docs/t-sql/functions/approx-count-distinct-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#348 fix "[集計関数 (&) #40 です。TRANSACT-SQL と #41 です。]"→"[集計関数 &#40;Transact-S…
  docs/t-sql/functions/count-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#347 fix "集計関数 (&) #40 です。TRANSACT-SQL と #41;."→"集計関数 &#40;Transact-SQL&#41;"
  docs/t-sql/functions/checksum-agg-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#346 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/avg-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#349 fix "[集計関数 (&) #40 です。TRANSACT-SQL と #41 です。]"→"[集計関数 &#40;Transact-S…
  docs/t-sql/functions/count-big-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#325 fix "データ ソース & #40; を作成します。SSAS 多次元 & #41;"→"データ ソースの作成 &#40;SSAS 多次元…
  docs/analysis-services/multidimensional-models/data-sources-in-multidimensional-models.md
Labels: Accepted

#327 [LOC] Back-Translation "現在"→"Current"
  docs/mdx/current-mdx.md
Labels: Accepted

#326 [LOC] Back-Translation "先祖"→"Ancestor"
  docs/mdx/ancestor-mdx.md
Labels: Accepted

#331 [LOC] Back-Translation "リードの (MDX)"→"Lead (MDX)"
  docs/mdx/lead-mdx.md
Labels: Accepted

#330 [LOC] Back-Translation "(MDX) を生成します。"→"Generate (MDX)"
  docs/mdx/generate-mdx.md
Labels: Accepted

#329 [LOC] Back-Translation ”除算”→"Divide"
  docs/mdx/divide-mdx.md
Labels: Accepted

#328 [LOC] Back-Translation "子メンバー"→"Cousin"
  docs/mdx/cousin-mdx.md
Labels: Accepted

#332 [LOC] Back-Translation "リーフ"→"Leaves"
  docs/mdx/leaves-mdx.md
Labels: Accepted

#338 [LOC] Back-Translation "ランク"→"Rank"
  docs/mdx/rank-mdx.md
Labels: Accepted

#337 [LOC] Back-Translation "プロパティ"→"Properties"
  docs/mdx/properties-mdx.md
Labels: Accepted

#334 [LOC] Back-Translation "名前"→"Name"
  docs/mdx/name-mdx.md
Labels: Accepted

#333 [LOC] Back-Translation "レベル"→"Levels"
  docs/mdx/levels-mdx.md
Labels: Accepted

#340 [LOC] Back-Translation "共用体"→"Union"
  docs/mdx/union-mdx.md
Labels: Accepted

#339 [LOC] Back-Translation "ルート"→"Root"
  docs/mdx/root-mdx.md
Labels: Accepted

#344 [LOC] Back-Translation "コマンド"→"Command"
  docs/mdx/vba-functions-in-mdx-and-dax.md
Labels: Accepted

#343 [LOC] Back-Translation "Varp 関数"→"VarP"
  docs/mdx/varp-mdx.md
Labels: Accepted

#342 [LOC] Back-Translation "差異 (MDX)"→"Variance (MDX)"
  docs/mdx/variance-mdx.md
Labels: Accepted

#341 [LOC] Back-Translation "ユーザー名 (MDX)"→"UserName (MDX)"
  docs/mdx/username-mdx.md
Labels: Accepted

#314 fix "Precision、scale、および長さ"→"有効桁数、小数点以下桁数、長さ"
  docs/t-sql/data-types/precision-scale-and-length-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#350 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/varp-transact-sql.md
Labels: Accepted

#357 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/var-transact-sql.md
Labels: Accepted

#356 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/sum-transact-sql.md
Labels: Accepted

#355 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/stdevp-transact-sql.md
Labels: Accepted

#354 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/stdev-transact-sql.md
Labels: Accepted

#353 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/min-transact-sql.md
Labels: Accepted

#352 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/max-transact-sql.md
Labels: Accepted

#351 Typo "COUNT_BIG (-SQL)"→"COUNT_BIG (Transact-SQL)"
  docs/t-sql/functions/count-big-transact-sql.md
Labels: Accepted

#358 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/lag-transact-sql.md
Labels: Accepted

#362 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/queries/select-order-by-clause-transact-sql.md
Labels: Accepted

#363 fix "[順位付け関数 (&) #40 です。TRANSACT-SQL と #41 です。]→"[順位付け関数 &#40;Transac…
  docs/t-sql/functions/dense-rank-transact-sql.md
Labels: Accepted

#297 Update grant-permissions-on-data-mining-structures-and-models-analysi…
  docs/analysis-services/multidimensional-models/grant-permissions-on-data-mining-structures-and-models-analysis-services.md
Labels: Accepted, Linguistic Suggestion

#366 fix " & #40 です。Analysis Services & #41;"→" &#40;Analysis Services&#41;"
  docs/analysis-services/multidimensional-models/grant-process-permissions-analysis-services.md
Labels: Accepted

#365 fix "#40 です。Analysis Services - データ マイニング & #41;"→"&#40;Analysis Services - データ マイニング&#41;"
  docs/analysis-services/data-mining/processing-data-mining-objects.md
Labels: Accepted

#367 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/rank-transact-sql.md
Labels: Accepted

#371 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]"→"[OVER 句 &#40;Transact-SQL…
  docs/t-sql/functions/percentile-disc-transact-sql.md
Labels: Accepted

#370 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]"→"[OVER 句 &#40;Transact-SQL…
  docs/t-sql/language-elements/expressions-transact-sql.md
Labels: Accepted

#369 fix "集計関数を使用して、"→"集計関数の使用"
  docs/analysis-services/multidimensional-models/use-aggregate-functions.md
Labels: Accepted

#368 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]"→"[OVER 句 &#40;Transact-SQL…
  docs/t-sql/functions/row-number-transact-sql.md
Labels: Accepted

#374 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]"→"[OVER 句 &#40;Transact-SQL…
  docs/t-sql/functions/lead-transact-sql.md
Labels: Accepted

#372 fix " [ は、FROM]"→" [ FROM]"
  docs/t-sql/functions/ntile-transact-sql.md
Labels: Accepted

#375 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;TRANSACT-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-sql-text-transact-sql.md
Labels: Accepted

#377 [LOC] Back-Translation "プレフィックス"→"prefix"
  docs/t-sql/functions/openxml-transact-sql.md
Labels: Accepted

#376 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;TRANSACT-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-text-query-plan-transact-sql.md
Labels: Accepted

#380 fix " & #40 です。Analysis Services & #41;"→" &#40;Analysis Services&#41;"
  docs/analysis-services/multidimensional-models/configure-string-storage-for-dimensions-and-partitions.md
Labels: Accepted

#379 fix "アソシエーション モデル & #40; のマイニング モデル コンテンツ"→" &#40;Analysis Services -…
  docs/analysis-services/data-mining/microsoft-association-algorithm.md
Labels: Accepted

#378 fix " (&) #40";"データベース エンジン"&"#41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/data-types/bit-transact-sql.md
Labels: Accepted

#373 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]"→"[OVER 句 &#40;Transact-SQ…
  docs/t-sql/functions/percentile-cont-transact-sql.md
Labels: Accepted

#381 fix "[経由句 (&) #40 です。TRANSACT-SQL と #41;]→"[OVER 句 &#40;Transact-SQL&…
  docs/t-sql/functions/avg-transact-sql.md
Labels: Accepted

#382 fix "& #40 です。Analysis Services & #41; "→"&#40;Analysis Services&#41;"
  docs/analysis-services/multidimensional-models/grant-permissions-on-a-data-source-object-analysis-services.md
Labels: Accepted

#383 fix "& #40 です。コメント & #41;& #40 です。MDX と #41 です。"→"&#40;コメント&#41; &#40…
  docs/analysis-services/multidimensional-models/mdx/supported-mdx-mdx.md
Labels: Accepted

#384 fix "ALTER CUBE ステートメント & #40 です。MDX と #41 です。"→"ALTER CUBE ステートメント &…
  docs/analysis-services/multidimensional-models/mdx/mdx-cell-calculations-build-cell-calculations.md
Labels: Accepted

#391 fix "MDX 言語リファレンス & #40 です。MDX と #41 です。"→"MDX 言語リファレンス &#40;MDX&#41;"
  docs/analysis-services/multidimensional-models/mdx/mdx-scripting-fundamentals-analysis-services.md
Labels: Accepted

#390 fix "データベース スコープ ベースの資格情報を変更します。"→"ALTER DATABASE SCOPED CREDENTIAL"
  docs/relational-databases/system-catalog-views/sys-database-credentials-transact-sql.md
Labels: In Progress

#389 fix "DB_NAME (&) #40 です。TRANSACT-SQL と #41 です。"→"DB_NAME &#40;TRANSAC…
  docs/t-sql/functions/version-transact-sql-metadata-functions.md
Labels: Accepted

#388 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;TRANSACT-SQL&#41;"
  docs/relational-databases/system-stored-procedures/sp-releaseapplock-transact-sql.md
Labels: Accepted

#387 fix "requests (&) #40 です。TRANSACT-SQL と #41 です。"→"requests &#40;TRANS…
  docs/relational-databases/system-functions/sys-fn-pagerescracker-transact-sql.md
Labels: In Progress

#386 [LOC] Back-Translation "言語を設定する"→"SET LANGUAGE"
  docs/relational-databases/system-stored-procedures/sp-helplanguage-transact-sql.md
Labels: Accepted

#385 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;TRANSACT-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-cached-plan-dependent-objects-transact-sql.md
Labels: Accepted

#393 Suggest to fix a code block
  docs/ssms/troubleshoot/ssms-troubleshoot.md
Labels: Accepted, Linguistic Suggestion

#395 [LOC] Back-Translation "アップグレード"→"upgrade"
  docs/relational-databases/system-stored-procedures/sp-helplanguage-transact-sql.md
Labels: Accepted

#394 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/language-elements/not-greater-than-transact-sql.md
Labels: Accepted

#396 fix "外部データ ソースの作成"→"CREATE EXTERNAL DATA SOURCE"
  docs/relational-databases/system-stored-procedures/sp-execute-remote-azure-sql-database.md
Labels: Accepted

#397 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/statements/create-asymmetric-key-transact-sql.md
Labels: Accepted

#398 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/statements/revoke-symmetric-key-permissions-transact-sql.md
Labels: Accepted

#399 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/idle-transact-sql.md
Labels: Accepted

#400 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/statements/create-master-key-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#406 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/language-elements/greater-than-transact-sql.md
Labels: Accepted

#405 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/timeticks-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#403 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;TRANSACT-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-exec-query-plan-stats-transact-sql.md
Labels: Accepted

#402 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→" &#40;Transact-SQL&#41;"
  docs/t-sql/functions/checksum-transact-sql.md
Labels: Accepted

#401 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/binary-checksum-transact-sql.md
Labels: Accepted

#392 fix "テーブル ヒント & #40 です。TRANSACT-SQL と #41 です"→"テーブル ヒント &#40;Transact…
  docs/relational-databases/system-dynamic-management-views/sys-dm-tran-locks-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#432 [LOC] Back-Translation "子孫"→"Descendants"
  docs/mdx/descendants-mdx.md
Labels: Accepted

#431 [LOC] Back-Translation "生成"→"Generate"
  docs/mdx/generate-mdx.md
Labels: Accepted

#428 [LOC] Back-Translation "選択"→"SELECT"
  docs/dmx/dmx-statements-data-manipulation.md
Labels: Accepted

#413 fix "組"→"タプル"
  docs/relational-databases/databases/databases.md
Labels: Accepted

#412 fix "組"→"タプル"
  docs/mdx/using-tuple-functions.md
Labels: Accepted

#421 fix "組"→"タプル"
  docs/mdx/strtotuple-mdx.md
Labels: Accepted

#420 fix "組"→"タプル"
  docs/relational-databases/system-catalog-views/sys-server-sql-modules-transact-sql.md
Labels: Accepted

#419 fix "組"→"タプル"
  docs/mdx/item-tuple-mdx.md
Labels: Accepted

#418 fix "組"→"タプル"
  docs/mdx/using-set-expressions.md
Labels: Accepted

#416 fix "組"→"タプル"
  docs/analysis-services/multidimensional-models/mdx/working-with-members-tuples-and-sets-mdx.md
Labels: Accepted

#426 fix "組"→"タプル"
  docs/relational-databases/system-catalog-views/sys-column-store-row-groups-transact-sql.md
Labels: Accepted

#425 fix "組"→"タプル"
  docs/mdx/count-tuple-mdx.md
Labels: Accepted

#424 fix "組"→"タプル"
  docs/analysis-services/multidimensional-models/mdx/mdx-data-modification-modifying-data.md
Labels: Accepted

#423 fix "組"→"タプル"
  docs/mdx/item-member-mdx.md
Labels: Accepted

#422 fix "組"→"タプル"
  docs/analysis-services/multidimensional-models/mdx/calculation-context.md
Labels: Accepted

#415 [LOC] Back-Translation "先祖"→"Ancestor"
  docs/mdx/ancestor-mdx.md
Labels: Accepted

#414 [LOC] Back-Translation "先祖"→"Ancestors"
  docs/mdx/ancestors-mdx.md
Labels: Accepted

#411 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/statements/deny-symmetric-key-permissions-transact-sql.md
Labels: Accepted

#410 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/language-elements/not-less-than-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#409 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/t-sql/functions/total-write-transact-sql.md
Labels: Accepted

#408 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→" &#40;Transact-SQL&#41;"
  docs/t-sql/functions/ident-seed-transact-sql.md
Labels: Accepted

#407 [LOC] Back-Translation "エッジの制約を作成します。"→"CREATE EDGE CONSTRAINTS"
  docs/relational-databases/graphs/sql-graph-architecture.md
Labels: Accepted

#433 fix "経由 句"→"OVER 句"
  docs/t-sql/functions/next-value-for-transact-sql.md
Labels: Accepted

#427 [LOC] Back-Translation "場所句"→"WHERE 句"
  docs/odbc/microsoft/where-clause-limitations.md
Labels: Accepted, Linguistic Suggestion

#434 fix "経由 句"→"OVER 句"
  docs/t-sql/functions/next-value-for-transact-sql.md
Labels: Accepted

#429 fix "組"→"タプル"
  docs/mdx/item-tuple-mdx.md
Labels: Accepted, Linguistic Suggestion

#430 [LOC] Back-Translation "生成"→"Generate"
  docs/mdx/current-mdx.md
Labels: Accepted, Linguistic Suggestion

#437 fix "& #40 を参照してください。TRANSACT-SQL と #41 です。"→" &#40;Transact-SQL&#41;"
  docs/relational-databases/clr-integration-database-objects-user-defined-types/working-with-user-defined-types-defining-udt-tables-and-columns.md
Labels: Accepted, Linguistic Suggestion

#439 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→" &#40;Transact-SQL&#41;"
  docs/relational-databases/clr-integration/monitoring-and-troubleshooting-managed-database-objects.md
Labels: Accepted

#443 [LOC] Back-Translation "先祖関数"→"Ascendants関数"
  docs/mdx/ascendants-mdx.md
Labels: Accepted

#446 [LOC] Back-Translation "選択"→"SELECT"
  docs/odbc/reference/develop-app/executing-catalog-functions.md
Labels: Accepted

#447 [LOC] Back-Translation "SELECT FROM&lt;モデル&gt;します。SAMPLE_CASES"→"SELE…
  docs/dmx/select-from-model-sample-cases-dmx.md
Labels: Accepted

#436 [LOC] Back-Translation "場所句"→"WHERE 句"
  docs/dmx/understanding-the-dmx-select-statement.md
Labels: Accepted, Linguistic Suggestion
