Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2019-08, with the labels that each got.

#449 [LOC] Back-Translation ”できません (Transact SQL) |マイクロソフトのドキュメント"→"FREETE…
  docs/relational-databases/system-functions/freetexttable-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#445 Suggest to fix case
  docs/advanced-analytics/index.yml
Labels: Accepted, Linguistic Suggestion

#450 [LOC] Back-Translation ”場所句"→"WHERE句"
  docs/relational-databases/system-functions/sys-fn-get-audit-file-transact-sql.md
Labels: Accepted

#453 [LOC] Back-Translation ”できません"→"FREETEXTTABLE"
  docs/relational-databases/system-functions/freetexttable-transact-sql.md
Labels: Accepted

#440 [LOC] Back-Translation "場所句"→"WHERE 句"
  docs/dmx/select-dmx.md
Labels: Accepted, Linguistic Suggestion

#441 [LOC] Back-Translation "場所の句"→"WHERE 句"
  docs/odbc/reference/develop-app/sqldescribecol-and-sqlcolattribute.md
Labels: Accepted, Linguistic Suggestion

#442 [LOC] Back-Translation "場所句"→"WHERE 句"
  docs/odbc/reference/appendixes/constructing-searched-statements.md
Labels: Accepted, Linguistic Suggestion

#448 [LOC] Back-Translation "削除"→"DELETE"
  docs/odbc/reference/develop-app/update-delete-and-insert-statements.md
Labels: Accepted, Linguistic Suggestion

#451 fix "(& a) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;;"
  docs/relational-databases/system-stored-procedures/sp-posttracertoken-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#465 [LOC] Back-Translation "場所句"→"WHERE 句"
  docs/odbc/reference/syntax/sqlgettypeinfo-function.md
Labels: Accepted

#464 Typo "**&#42;&#42;重要な&#42; &#42;**"→"**重要**"
  docs/relational-databases/system-information-schema-views/check-constraints-transact-sql.md
Labels: Accepted

#463 Typo "-YYYY-MM-DD"→"YYYY-MM-DD"
  docs/t-sql/data-types/date-transact-sql.md
Labels: Accepted

#462 Typo "&#40;MDX&#41"→"&#40;MDX&#41;"
  docs/analysis-services/multidimensional-models/mdx/supported-mdx-mdx.md
Labels: Accepted

#460 Typo "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-dynamic-management-views/transaction-related-dynamic-management-views-and-functions-transact-sql.md
Labels: Accepted

#459 [LOC] Back-Translation "説明"→"Description"
  docs/odbc/microsoft/using-sqlconfigdatasource-with-the-odbc-driver-for-oracle.md
Labels: Accepted

#458 Typo "[DATE]"→"DATE"
  docs/odbc/microsoft/mapping-data-types-odbc-driver-for-oracle.md
Labels: Accepted

#457 Typo "[DATE]"→"DATE"
  docs/odbc/microsoft/supported-data-types-odbc-driver-for-oracle.md
Labels: Accepted

#456 [LOC] Back-Translation "選択`表`します。"→"SELECT `My Table`"
  docs/odbc/microsoft/core-level-api-functions-odbc-driver-for-oracle.md
Labels: Accepted

#455 [LOC] Back-Translation "サインイン"→"sign"
  docs/odbc/microsoft/sql-conformance-levels-odbc-driver-for-oracle.md
Labels: Accepted

#454 [LOC] Back-Translation error message
  docs/odbc/microsoft/revoking-and-granting-rights-when-using-stored-procedures.md
Labels: Accepted

#404 fix "トレースをフィルター処理"→"トレースへのフィルターの適用"
  docs/relational-databases/system-functions/sys-fn-get-sql-transact-sql.md
Labels: In Progress, Linguistic Suggestion

#461 fix "& #40 を参照してください。TRANSACT-SQL と #41 です"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-tran-locks-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#466 fixed inappropriate japanese "付録 b:。ODBC の状態遷移テーブルします。"→"付録 B:ODBC の状…
  docs/odbc/reference/develop-app/closing-the-cursor.md
Labels: Accepted, Linguistic Suggestion

#499 [LOC] Back-Translation "お試しください.キャッチしてください.最後に"→"Try...Catch...Finally"
  docs/relational-databases/server-management-objects-smo/create-program/handling-smo-exceptions.md
Labels: Accepted

#467 fix "& #40 を参照してください。TRANSACT-SQL と #41 です"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-index-usage-stats-transact-sql.md
Labels: Accepted

#469 fix "& #40 を参照してください。TRANSACT-SQL と #41 です"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-index-physical-stats-transact-sql.md
Labels: Accepted

#468 fix "& #40 を参照してください。TRANSACT-SQL と #41 です"→"&#40;Transact-SQL&#41;"
  docs/2014/2014-toc/sql-server-transaction-locking-and-row-versioning-guide.md
Labels: Accepted

#470 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→" &#40;Transact-SQL&#41;"
  docs/t-sql/functions/checksum-transact-sql.md
Labels: Accepted

#472 fix "(&) #40 です。TRANSACT-SQL と #41 です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-file-space-usage-transact-sql.md
Labels: Accepted

#471 fix "& #40 を参照してください。TRANSACT-SQL と #41 です"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-stored-procedures/sp-lock-transact-sql.md
Labels: Accepted

#474 [LOC] Back-Translation "など"→"LIKE"
  docs/odbc/reference/develop-app/like-predicate-escape-character.md
Labels: Accepted

#473 [LOC] Back-Translation "場所句"→"WHERE 句"
  docs/odbc/reference/develop-app/outer-joins.md
Labels: Accepted

#476 [LOC] Back-Translation "時間 *"→"Time*"
  docs/odbc/reference/develop-app/date-time-and-timestamp-literals.md
Labels: Accepted

#475 [LOC] Back-Translation "変換"→"CONVERT"
  docs/odbc/reference/develop-app/scalar-function-calls.md
Labels: Accepted

#478 [LOC] Back-Translation "選択"→"SELECT"
  docs/odbc/reference/develop-app/effect-of-transactions-on-cursors-and-prepared-statements.md
Labels: Accepted

#477 [LOC] Back-Translation "呼び出す"→"CALL"
  docs/odbc/reference/develop-app/types-of-descriptors.md
Labels: Accepted

#482 [LOC] Back-Translation "[データ ソース]"→"Data Source"
  docs/t-sql/functions/opendatasource-transact-sql.md
Labels: Accepted

#481 Typo "**&#42;&#42; 重要 &#42;&#42;**"→"**重要**"
  docs/t-sql/functions/openrowset-transact-sql.md
Labels: Accepted

#480 [LOC] Back-Translation "テキスト、 ntext、およびイメージ"→"text、 ntext、およびimage"
  docs/relational-databases/system-stored-procedures/sp-executesql-transact-sql.md
Labels: Accepted

#479 fixed inappropriate japanese "SqlHierarchyId**"→"**SqlHierarchyId**"
  docs/t-sql/data-types/read-database-engine.md
Labels: Accepted

#483 Typo "オプション"→”false"
  docs/t-sql/functions/openjson-transact-sql.md
Labels: Accepted

#487 Typo "[DATE]"→"DATE"
  docs/odbc/microsoft/data-type-limitations.md
Labels: Accepted

#484 [LOC] Back-Translation "テーブル作成ステートメント"→"CREATE TABLE ステートメント"
  docs/odbc/microsoft/limitations.md
Labels: Accepted

#497 fixed inappropriate japanese "場所 CURRENT OF 句の制限事項"→"WHERE CURRENT OF…
  docs/odbc/microsoft/where-current-of-clause-limitations.md
Labels: Accepted

#496 fixed inappropriate japanese "NULL 以外の制限事項"→"NOT NULL の制限事項"
  docs/odbc/microsoft/not-null-limitations.md
Labels: Accepted

#495 fixed inappropriate japanese "述語の制限事項など"→"LIKE 述語の制限事項"
  docs/odbc/microsoft/like-predicate-limitations.md
Labels: Accepted

#494 fixed inappropriate japanese "句の制限がある"→"HAVING 句の制限事項"
  docs/odbc/microsoft/having-clause-limitations.md
Labels: Accepted, Linguistic Suggestion

#493 fixed inappropriate japanese "句の制限事項から"→"FROM 句の制限事項"
  docs/odbc/microsoft/from-clause-limitations.md
Labels: Accepted, Linguistic Suggestion

#492 fixed inappropriate japanese "呼び出しステートメントの制限事項"→"CALL ステートメントの制限事項"
  docs/odbc/microsoft/call-statement-limitations.md
Labels: Accepted, Linguistic Suggestion

#491 fixed inappropriate japanese "述語の制限事項と"→"AND 述語の制限事項"
  docs/odbc/microsoft/and-predicate-limitations.md
Labels: Accepted, Linguistic Suggestion

#498 [LOC] Back-Translation "最初"→"First"
  docs/relational-databases/system-stored-procedures/sp-settriggerorder-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#488 fixed inappropriate japanese "制限事項を並べ替え"→"並べ替えの制限事項"
  docs/odbc/microsoft/sorting-limitations.md
Labels: Accepted, Linguistic Suggestion

#486 fixed inappropriate japanese "セット関数の制限事項"→"集合関数の制限事項"
  docs/odbc/microsoft/set-functions-limitations.md
Labels: Accepted, Linguistic Suggestion

#485 fixed inappropriate japanese "Word の制限に予約されています"→"予約済みキーワードの制限事項"
  docs/odbc/microsoft/reserved-word-limitations.md
Labels: Accepted, Linguistic Suggestion

#490 fixed inappropriate japanese "制限事項の表示"→"ビューの制限事項"
  docs/odbc/microsoft/views-limitations.md
Labels: Accepted, Linguistic Suggestion

#489 fixed inappropriate japanese "クエリの制限事項をパラメーター化された"→"パラメーター化クエリの制限事項"
  docs/odbc/microsoft/parameterized-query-limitations.md
Labels: Accepted, Linguistic Suggestion

#500 Fix "& #40 を参照してください。TRANSACT-SQL と #41 です"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sys-dm-db-task-space-usage-transact-sql.md
Labels: Accepted

#504 [LOC] Back-Translation "状態"→"State"
  docs/2014/tutorials/task-7-creating-a-composite-domain.md
Labels: Accepted

#503 [LOC] Back-Translation "状態"→"State"
  docs/2014/tutorials/task-8-creating-a-composite-domain-rule.md
Labels: Accepted

#501 [LOC] Back-Translation "状態"→"State"
  docs/2014/tutorials/task-1-creating-a-knowledge-base-and-domains.md
Labels: Accepted

#505 [LOC] Back-Translation "未割り当ての領域"→"unallocated space"
  docs/relational-databases/system-stored-procedures/sp-spaceused-transact-sql.md
Labels: Accepted

#509 [LOC] Back-Translation "選択ステートメント"→"SELECT ステートメント"
  docs/odbc/reference/develop-app/was-a-result-set-created.md
Labels: Accepted

#508 [LOC] Back-Translation "選択ステートメント"→"SELECT ステートメント"
  docs/odbc/reference/develop-app/retrieving-results-basic.md
Labels: Accepted, Source Issue

#511 [LOC] Back-Translation "選択"→"SELECT"
  docs/odbc/reference/develop-app/positioned-update-and-delete-statements.md
Labels: Accepted

#510 [LOC] Back-Translation "削除"→"DELETE"
  docs/odbc/reference/develop-app/updating-data-overview.md
Labels: Accepted

#514 [LOC] Back-Translation "更新"→"UPDATE"
  docs/odbc/reference/develop-app/updating-data-with-sqlbulkoperations.md
Labels: Accepted

#513 [LOC] Back-Translation "削除"→"DELETE"
  docs/odbc/reference/develop-app/updating-data-with-sqlsetpos.md
Labels: Accepted

#512 [LOC] Back-Translation "場所句"→"WHERE句"
  docs/odbc/reference/develop-app/simulating-positioned-update-and-delete-statements.md
Labels: Accepted

#516 [LOC] Back-Translation "選択"→"SELECT"
  docs/odbc/reference/syntax/sqlmoreresults-function.md
Labels: Accepted

#515 [LOC] Back-Translation "選択\*から従業員"→"SELECT \* FROM Employee"
  docs/odbc/reference/develop-app/statement-handles.md
Labels: Accepted

#560 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-sessions-transact-sql.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#550 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-current-partition-mappings.md
Labels: Accepted

#521 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-dynamic-management-views/sql-server-operating-system-related-dynamic-management-views-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#519 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msrepl-transactions-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#528 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/sysarticlecolumns-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#527 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/dbo-syssubsystems-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#526 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/syssubscriptions-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#523 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-views/ihsyscolumns-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#544 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mslogreader-history-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#541 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/sysmergepartitioninfo-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#540 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/sysmergearticles-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#539 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/sysmergearticlecolumns-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#538 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/sysarticleupdates-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#535 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mstracer-tokens-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#534 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mstracer-history-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#533 Typo "TRANSACT-SQL"→"Transact-SQL"
  docs/relational-databases/system-tables/mssync-states-transact-sql.md
Labels: Accepted

#554 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-identity-range-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#553 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-history-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#548 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-conflicts-info-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#547 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-altsyncpartners-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#557 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-partition-groups-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#517 [LOC] Back-Translation "conflict <スキーマ><テーブル>"→"conflict_<schema>_<ta…
  docs/relational-databases/system-tables/conflict-schema-table-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#522 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mssubscriber-schedule-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#520 [LOC] Back-Translation "される"→"schemaguid"
  docs/relational-databases/system-tables/sysmergeschemachange-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#518 [LOC] Back-Translation "MSmerge_競合_パブリケーション<アーティクル(transact-sql> )><_…
  docs/relational-databases/system-tables/msmerge-conflict-publication-article-transact-sql.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#531 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mssubscription-properties-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#530 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mssubscription-articles-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#529 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mssubscriber-info-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#525 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mssubscription-agents-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#524 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-conflictdetectionconfigrequest-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#543 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mslogreader-agents-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#542 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/sysmergepublications-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#537 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/sysarticles-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#532 Typo "**@subscriber_db**"→"**\@subscriber_db**"
  docs/relational-databases/system-tables/mssubscriptions-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#552 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-genhistory-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#551 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-generation-partition-mappings-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#549 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-contents-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#546 [LOC] Back-Translation "挿入します"→"inserts"
  docs/relational-databases/system-tables/msmerge-articlehistory-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#545 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-agents-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#559 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-replinfo-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#558 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-past-partition-mappings-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#556 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-metadataaction-request-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#555 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-identity-range-allocations-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#570 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-topologyrequest-transact-sql.md
Labels: Accepted

#568 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-request-transact-sql.md
Labels: Accepted

#567 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-originatorid-history-transact-sql.md
Labels: Accepted

#566 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-lsns-transact-sql.md
Labels: Accepted

#565 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-conflictdetectionconfigresponse-transact-sql.md
Labels: Accepted

#564 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-conflictdetectionconfigrequest-transact-sql.md
Labels: Accepted

#563 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-tombstone-transact-sql.md
Labels: Accepted

#562 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-subscriptions-transact-sql.md
Labels: Accepted

#561 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msmerge-settingshistory-transact-sql.md
Labels: Accepted

#572 Typo Del→DELETE
  docs/2014/2014-toc/sql-server-transaction-locking-and-row-versioning-guide.md
Labels: Accepted

#571 fix ピア→peer
  docs/relational-databases/system-tables/mspeer-topologyresponse-transact-sql.md
Labels: Accepted

#569 [LOC] Back-Translation "ピア"→"peer"
  docs/relational-databases/system-tables/mspeer-response-transact-sql.md
Labels: Accepted

#573 Typo "**@namespace=**"→"**\@namespace=**"
  docs/relational-databases/system-stored-procedures/sp-settriggerorder-transact-sql.md
Labels: Linguistic Suggestion, Partially Accepted

#579 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspublicationthresholds-transact-sql.md
Labels: Accepted

#578 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspublications-transact-sql.md
Labels: Accepted

#577 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspublication-access-transact-sql.md
Labels: Accepted

#576 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspub-identity-range-transact-sql.md
Labels: Accepted

#575 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-topologyresponse-transact-sql.md
Labels: Accepted

#574 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mspeer-topologyrequest-transact-sql.md
Labels: Accepted

#588 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;
  docs/relational-databases/system-tables/msrepl-queuedtraninfo-transact-sql.md
Labels: Accepted

#587 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;
  docs/relational-databases/system-tables/msrepl-originators-transact-sql.md
Labels: Accepted

#586 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;
  docs/relational-databases/system-tables/msrepl-identity-range-transact-sql.md
Labels: Accepted

#585 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;
  docs/relational-databases/system-tables/msrepl-errors-transact-sql.md
Labels: Accepted

#584 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msrepl-commands-transact-sql.md
Labels: Accepted

#583 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;
  docs/relational-databases/system-tables/msrepl-backup-lsns-transact-sql.md
Labels: Accepted

#582 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;
  docs/relational-databases/system-tables/msqreader-history-transact-sql.md
Labels: Accepted

#581 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;
  docs/relational-databases/system-tables/msqreader-agents-transact-sql.md
Labels: Accepted

#591 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msreplication-monitordata-transact-sql.md
Labels: Accepted

#590 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msrepl-version-transact-sql.md
Labels: Accepted

#589 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msrepl-transactions-transact-sql.md
Labels: Accepted

#594 fix "& #40 を参照してください。TRANSACT-SQL と #41 です"→"&#40;Transact-SQL&#41;"
  docs/2014/2014-toc/sql-server-transaction-locking-and-row-versioning-guide.md
Labels: Accepted

#593 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mslogreader-agents-transact-sql.md
Labels: Accepted

#580 [LOC] Back-Translation "標準"→"Standard"
  docs/relational-databases/system-tables/mspublisher-databases-transact-sql.md
Labels: Accepted, Linguistic Suggestion

#592 [LOC] Back-Translation "削除"→"DELETE","挿入"→"INSERT"
  docs/odbc/reference/develop-app/determining-the-number-of-affected-rows.md
Labels: Accepted, Linguistic Suggestion

#598 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;
  docs/relational-databases/system-tables/msreplication-queue-transact-sql.md
Labels: Accepted

#599 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/msreplication-subscriptions-transact-sql.md
Labels: Accepted

#601 fix "&#40; です。TRANSACT-SQL と &#41; です。"→"&#40;Transact-SQL&#41;"
  docs/relational-databases/system-tables/mssnapshot-agents-transact-sql.md
Labels: Accepted
