Repository MicrosoftDocs/sql-docs.ja-jp, pull requests merged in 2020-05, with the labels that each got.

#956 [LOC]Back-Translation "[表示]\(表示\) "→"[View]\(表示\) "
  docs/big-data-cluster/spark-hive-tools-vscode.md
Labels: Accepted, P1

#955 Fix "resolution"
  docs/big-data-cluster/troubleshoot-active-directory.md
  docs/big-data-cluster/troubleshoot-ad-reverse-lookup-zone.md
  docs/big-data-cluster/troubleshoot-hdfs-restore-admin.md
  docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md
  docs/integration-services/change-data-capture/known-issues-resolutions-with-cdc-for-oracle-attunity.md
  docs/relational-databases/errors-events/mssqlserver-824-database-engine-error.md
  docs/relational-databases/in-memory-oltp/resolve-out-of-memory-issues.md
  docs/relational-databases/in-memory-oltp/transact-sql-constructs-not-supported-by-in-memory-oltp.md
Labels: Accepted, Linguistic Suggestion, P0

#958 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  docs/azure-data-studio/integrated-terminal.md
Labels: Accepted, Linguistic Suggestion, P1

#959 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  docs/azure-data-studio/release-notes-azure-data-studio.md
Labels: Accepted, Linguistic Suggestion, P1

#957 [LOC]Fixed inappropriate japanese "[ビュー]"→"[表示]"
  docs/big-data-cluster/notebooks-manage-bdc.md
Labels: Accepted, Linguistic Suggestion, P1

#960 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  docs/azure-data-studio/release-notes-azure-data-studio.md
Labels: Accepted, Linguistic Suggestion, P1

#961 Fix typo
  docs/reporting-services/application-integration/release-notes-ssrs-application-integration.md
Labels: Accepted, Linguistic Suggestion, P1

#963 [LOC]Fixed inappropriate japanese "複製"→"クローン"
  docs/sql-server/sql-server-docs-contribute.md
Labels: Accepted, Linguistic Suggestion, P1

#962 Update server-configuration-options-sql-server.md
  docs/database-engine/configure-windows/server-configuration-options-sql-server.md
Labels: Accepted, Linguistic Suggestion, P1

#964 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  docs/big-data-cluster/deploy-with-kubeadm.md
Labels: Accepted, Linguistic Suggestion, P1

#965 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  docs/database-engine/availability-groups/windows/availability-group-lease-healthcheck-timeout.md
Labels: Accepted, Linguistic Suggestion, P1

#967 Update nchar-and-nvarchar-transact-sql.md
  docs/t-sql/data-types/nchar-and-nvarchar-transact-sql.md
Labels: Accepted, P1, Technical Issue
